services:
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    # Limiting memory usage
    memoryLimit: 512M
